# Generated by Django 4.1.5 on 2024-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_photos/%Y/%m/%d/', verbose_name='Фото пользователя'),
        ),
    ]
