version: "3.10"

volumes:
  pgdata_pit:
  pgdata:
  static_pit:
  media_pit:
  static:
  media:

services:

  django_pit:
    build:
      context: ./sitesportpit-back
    ports:
      - '8001:8000'
    container_name: django_pit
    env_file:
      - ./sitesportpit-back/docker/env/.env.prod
    volumes:
      - ./sitesportpit-back/:/app
      - static_pit:/app/static
      - media_pit:/app/media
    depends_on:
      - postgres_pit
      - redis_pit
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --workers=4 --reload --max-requests=1000 sportpit.wsgi -b 0.0.0.0:8000"

  django:
    build:
      context: ./shopmoderno
    ports:
      - '8002:8000'
    container_name: django
    env_file:
      - ./shopmoderno/docker/env/.env.prod
    volumes:
      - ./shopmoderno/:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
      - redis
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn --workers=4 --reload --max-requests=1000 shopmoderno.wsgi -b 0.0.0.0:8000"

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_pit:/app/static
      - media_pit:/app/media
      - static:/app/static
      - media:/app/media
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - django_pit
      - django

  postgres_pit:
    image: postgres:alpine
    container_name: postgres_pit
    restart: always
    env_file:
      - ./sitesportpit-back/docker/env/.env.prod
    volumes:
      - pgdata_pit:/var/lib/postgresql/data/

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file:
      - ./shopmoderno/docker/env/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis_pit:
    image: redis:alpine
    container_name: redis_pit
    env_file:
      - ./sitesportpit-back/docker/env/.env.prod
    expose:
      - 6379
    volumes:
      - ./sitesportpit-back/docker/redis/data:/data

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - ./shopmoderno/docker/env/.env.prod
    expose:
      - 6379
    volumes:
      - ./shopmoderno/docker/redis/data:/data

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt:rw
        - ./nginx/certbot/www:/var/www/certbot:rw
    depends_on:
      - nginx
