# Generated by Django 4.1.5 on 2024-03-31 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (Формируется автоматически)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название продукта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (Формируется автоматически)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_published', models.BooleanField(default=1)),
                ('price', models.FloatField(blank=True, default=100, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='img')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления статьи')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='Оценка')),
                ('product_review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='product.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-create_date',),
            },
        ),
    ]
