# Generated by Django 4.1.5 on 2024-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Номер дома')),
                ('basket', models.TextField(verbose_name='Корзина')),
            ],
        ),
    ]
