# Generated by Django 4.1.5 on 2024-04-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_discount_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='Цена'),
        ),
    ]
